# Generated by Django 4.0.3 on 2022-05-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_flight_transition_aiport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='transition_aiport',
            new_name='transition_aiports',
        ),
    ]
