# Generated by Django 4.0.3 on 2022-05-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_reservation_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_booked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='is_applied',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
