# Generated by Django 4.0.3 on 2022-05-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ticket_is_booked_alter_policy_is_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='blank.jpg', null=True, upload_to=''),
        ),
    ]
