# Generated by Django 4.0.4 on 2022-06-01 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ('-id',)},
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='transition_aiports',
            new_name='transition_airports',
        ),
    ]
