# Generated by Django 4.0.4 on 2022-06-01 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_airport_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='transition_airports',
        ),
        migrations.AddField(
            model_name='flight',
            name='transition_airports',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.transitionairport'),
        ),
    ]
