# Generated by Django 4.0.4 on 2022-06-01 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_flight_transition_airports_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='transition_airports',
        ),
        migrations.AddField(
            model_name='transitionairport',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.flight'),
        ),
    ]
